#
# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Configuration file for Docs Agent

# `product_name` is the name of your product that appears on the chatbot UI.
product_name: "My product"

# `output_path` is the directory where the plain text files will be saved
# after Markdown files are processed by `markdown-to-plain-text.py`. It is
# relative to the Doc Agent repo folder.
output_path: "data/plain_docs"

# `vector_db_dir` is the directory that stores artifacts for the Chroma vector
# database.
vector_db_dir: "vector_stores/chroma"

# `collection_name` is the name used by the Chroma vector database to identify
# your dataset collection.
collection_name: "docs_collection"

# You can list a number of input sources under the `input` field:
# `path` (Required):         The directory where the source Markdown files are
#                            stored.
# `url_prefix` (Required):   The prefix of the URL used to create URLs for the
#                            source files. If URLs don't exist for the source
#                            files, you still need to provide a mock string.
# `exclude_path` (Optional): The sub-directory to be excluded from the `path`
#                            directory when processing source files.
input:
  - path: "data/example/markdown-src-01"
    url_prefix: "https://example.com/markdown-src-01"
  - path: "data/example/markdown-src-02"
    url_prefix: "https://example.com/makrdown-src-02"
    exclude_path: "/reference/changelogs/"

